import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        k: {
          purple:        "#4C1D6E",
          "purple-dark": "#3A1254",
          "purple-darker":"#280D3B",
          "purple-light": "#6B2D96",
          "purple-mid":   "#7C3EA8",
          "purple-tint":  "#F3EEFA",
          "purple-tint2": "#E8D8F8",
          yellow:         "#FFC700",
          "yellow-dark":  "#E6B400",
          "yellow-darker":"#CC9F00",
          "yellow-light": "#FFF3CC",
          "yellow-text":  "#1A1000",
        },
      },
      fontFamily: {
        sans:    ["Inter", "-apple-system", "sans-serif"],
        sinhala: ["Noto Sans Sinhala", "Inter", "sans-serif"],
        tamil:   ["Noto Sans Tamil",   "Inter", "sans-serif"],
      },
      borderRadius: {
        card: "12px",
        "4xl": "28px",
      },
      boxShadow: {
        card:       "0 2px 8px rgba(76,29,110,0.08)",
        "card-hover":"0 8px 24px rgba(76,29,110,0.18)",
        "yellow-glow":"0 4px 20px rgba(255,199,0,0.45)",
        "purple-glow":"0 4px 20px rgba(76,29,110,0.35)",
        modal:      "0 24px 64px rgba(0,0,0,0.22)",
      },
      animation: {
        "fade-up":        "fadeUp 0.28s cubic-bezier(0.16,1,0.3,1)",
        "fade-in":        "fadeIn 0.2s ease-out",
        "slide-right":    "slideRight 0.38s cubic-bezier(0.16,1,0.3,1)",
        "slide-up":       "slideUp 0.38s cubic-bezier(0.16,1,0.3,1)",
        "scale-in":       "scaleIn 0.22s cubic-bezier(0.34,1.56,0.64,1)",
        "bounce-press":   "bouncePress 0.3s cubic-bezier(0.34,1.56,0.64,1)",
        "spin-slow":      "spin 2s linear infinite",
        "shimmer":        "shimmer 1.4s ease-in-out infinite",
        "float":          "float 3s ease-in-out infinite",
        "pulse-ring":     "pulseRing 2s ease-out infinite",
        "typing-dot":     "typingDot 1.2s ease-in-out infinite",
        "cart-bounce":    "cartBounce 0.5s cubic-bezier(0.34,1.56,0.64,1)",
      },
      keyframes: {
        fadeUp:     { "0%": { opacity:"0", transform:"translateY(14px)" },
                      "100%":{ opacity:"1", transform:"translateY(0)"   } },
        fadeIn:     { "0%": { opacity:"0" }, "100%":{ opacity:"1" } },
        slideRight: { "0%": { transform:"translateX(100%)" },
                      "100%":{ transform:"translateX(0)" } },
        slideUp:    { "0%": { transform:"translateY(20px)", opacity:"0" },
                      "100%":{ transform:"translateY(0)",   opacity:"1" } },
        scaleIn:    { "0%": { transform:"scale(0.9)",  opacity:"0" },
                      "100%":{ transform:"scale(1)",   opacity:"1" } },
        bouncePress:{ "0%": { transform:"scale(1)"   },
                      "40%":{ transform:"scale(0.94)" },
                      "70%":{ transform:"scale(1.04)" },
                      "100%":{ transform:"scale(1)"  } },
        float:      { "0%,100%":{ transform:"translateY(0)"  },
                      "50%":     { transform:"translateY(-6px)" } },
        pulseRing:  { "0%":   { transform:"scale(1)",    opacity:"0.7" },
                      "100%": { transform:"scale(1.18)", opacity:"0"   } },
        typingDot:  { "0%,60%,100%":{ transform:"translateY(0)"  },
                      "30%":         { transform:"translateY(-7px)" } },
        cartBounce: { "0%":  { transform:"scale(1)"    },
                      "30%": { transform:"scale(1.35)" },
                      "60%": { transform:"scale(0.9)"  },
                      "80%": { transform:"scale(1.1)"  },
                      "100%":{ transform:"scale(1)"    } },
      },
    },
  },
  plugins: [],
};
export default config;
