// Static UI strings in all 4 languages
export const UI_STRINGS = {
  en: {
    placeholder:    "What are you looking for?",
    thinking:       "Kavi is thinking...",
    addToCart:      "Add to Cart",
    checkout:       "Checkout",
    trackOrder:     "Track Order",
    payNow:         "Pay Now",
    giftMessage:    "Add a gift message",
    deliveryDate:   "Choose delivery date",
    cartTitle:      "Shopping Cart",
    emptyCart:      "Your cart is empty",
    total:          "Total",
    items:          "items",
    subtotal:       "Subtotal",
    deliveryFee:    "Delivery Fee",
    recipientName:  "Recipient Name",
    phone:          "Phone Number",
    address:        "Delivery Address",
    city:           "City",
    confirmOrder:   "Confirm Order",
    giftSender:     "Your Name (Sender)",
    viewDetails:    "View Details",
    close:          "Close",
  },
  si: {
    placeholder:    "ඔබ සොයන්නේ කුමක්ද?",
    thinking:       "කවි සිතනවා...",
    addToCart:      "කරත්තයට එකතු කරන්න",
    checkout:       "ගෙවීම සිදු කරන්න",
    trackOrder:     "ඇණවුම සොයන්න",
    payNow:         "දැන් ගෙවන්න",
    giftMessage:    "තෑගි පණිවිඩයක් එකතු කරන්න",
    deliveryDate:   "බෙදා හැරීමේ දිනය තෝරන්න",
    cartTitle:      "මිලදී ගැනුම් කරත්තය",
    emptyCart:      "ඔබේ කරත්තය හිස් ය",
    total:          "මුළු එකතුව",
    items:          "භාණ්ඩ",
    subtotal:       "උප එකතුව",
    deliveryFee:    "බෙදා හැරීමේ ගාස්තුව",
    recipientName:  "ලබන්නාගේ නම",
    phone:          "දුරකථන අංකය",
    address:        "බෙදා හැරීමේ ලිපිනය",
    city:           "නගරය",
    confirmOrder:   "ඇණවුම තහවුරු කරන්න",
    giftSender:     "ඔබේ නම (යවන්නා)",
    viewDetails:    "විස්තර බලන්න",
    close:          "වසා දමන්න",
  },
  ta: {
    placeholder:    "நீங்கள் என்ன தேடுகிறீர்கள்?",
    thinking:       "கவி யோசிக்கிறான்...",
    addToCart:      "கார்ட்டில் சேர்க்கவும்",
    checkout:       "செலுத்தவும்",
    trackOrder:     "ஆர்டரை கண்காணிக்கவும்",
    payNow:         "இப்போது பணம் செலுத்தவும்",
    giftMessage:    "பரிசு செய்தி சேர்க்கவும்",
    deliveryDate:   "டெலிவரி தேதி தேர்ந்தெடுக்கவும்",
    cartTitle:      "ஷாப்பிங் கார்ட்",
    emptyCart:      "உங்கள் கார்ட் காலியாக உள்ளது",
    total:          "மொத்தம்",
    items:          "பொருட்கள்",
    subtotal:       "துணைத் தொகை",
    deliveryFee:    "டெலிவரி கட்டணம்",
    recipientName:  "பெறுநரின் பெயர்",
    phone:          "தொலைபேசி எண்",
    address:        "டெலிவரி முகவரி",
    city:           "நகரம்",
    confirmOrder:   "ஆர்டரை உறுதிப்படுத்தவும்",
    giftSender:     "உங்கள் பெயர் (அனுப்புநர்)",
    viewDetails:    "விவரங்களைக் காட்டு",
    close:          "மூடு",
  },
  tanglish: {
    placeholder:    "Enna thedum? Type here machan!",
    thinking:       "Kavi yosikiran...",
    addToCart:      "Cart-la poduvom",
    checkout:       "Pay pannuvom",
    trackOrder:     "Order track pannuvom",
    payNow:         "Pay Now da",
    giftMessage:    "Gift message poduvom",
    deliveryDate:   "Delivery date choose pannuvom",
    cartTitle:      "Shopping Cart machan",
    emptyCart:      "Cart empty-ஆ இருக்கு brother",
    total:          "Total count",
    items:          "items items",
    subtotal:       "Subtotal pathuko",
    deliveryFee:    "Delivery charges",
    recipientName:  "Recipient Name machan",
    phone:          "Phone number podu",
    address:        "Delivery address",
    city:           "City map",
    confirmOrder:   "Order confirm pannu",
    giftSender:     "Your name podu",
    viewDetails:    "Details paaru",
    close:          "Close panni vai",
  }
};
